install trivy 


Name   : Dileep
Gender : M
City   : Chittoor

name: Scan the Trivy for Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-scan:
    name: Trivy Scan Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy on Linux machine
        run: |
          sudo apt update -y && sudo apt upgrade -y
          sudo apt-get install wget -y
          wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh
          sudo bash install.sh
          trivy --version

      - name: Scan the file system (fs)
        run: |
          trivy fs .

      - name: Build the Docker image
        run: |
          docker build -t reactapp:latest .

      - name: Scan the Docker image
        run: |
          mkdir -p reports
          trivy image --format json -o "./reports/app_scan_report.json" reactapp:latest





